// <auto-generated />
namespace Optional.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class MigrateRerister : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MigrateRerister));
        
        string IMigrationMetadata.Id
        {
            get { return "201806021606234_MigrateRerister"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
